name: Generate Command Docs
on:
  push:
    paths:
      - 'src/groundStation/system.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
          architecture: 'x64'
      - name: Install numpy
        run: python3 -m pip install numpy
      - name: Generate Docs
        run: python3 src/docGen.py
      - name: Commit CommandDocs.txt
        run: git commit -m "Auto-updating CommandDocs.txt"
      - name: Push CommandDocs.txt
        run: git push
